### ISSUE TITLE
Strike in the 9th frame

### ISSUE THREAD

**Issue by joekur** [drewolson/bowling#1]
Hey, what's up Drew? (you may remember me from braintree). Found this from the elixir meetup group. Great exercise, I learned a lot from your solution.

I think I found an edge case that isn't properly handled - specifically if it's a strike in the 9th frame with no strikes/spares in the last. Eg the last 3 rolls of [10, 5, 3] gets interpreted as the last frame.

```elixir
test "strike in the 9th frame" do
  score = Bowling.score([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 5, 3])
  assert score == 26
end
```

Not sure if this is the best solution, but I solved it by keeping track of the frame:

```elixir
defmodule Bowling do
  def score(rolls) do
    score(rolls, 0, 1)
  end

  defp score(rolls, total, 10) do
    Enum.sum(rolls) + total
  end

  defp score([], total, frame) do
    total
  end

  defp score([10,a,b|rest], total, frame) do
    score([a,b|rest], total + 10 + a + b, frame + 1)
  end

  defp score([a,b,c|rest], total, frame) when a + b == 10 do
    score([c|rest], total + 10 + c, frame + 1)
  end

  defp score([a,b|rest], total, frame) do
    score(rest, total + a + b, frame + 1)
  end
end
```

Hope I'm not being nitpicky, just thought future elixir-learners might run into this.

**Comment by drewolson** [comment]
Hi, nice to hear from you again!

You're definitely correct, this is an edge case I don't correctly handle. I like the idea of adding the frame number, it works great. Do you want to submit a PR for this?

**Comment by joekur** [comment]
Can do!

**Comment by drewolson** [comment]
Fixed in the branch `solution` via your PR. Thanks!
